-- ============================================================
-- teech-platform Migration 005: Audit Log & Report Card
-- ============================================================
-- Transparency principle: every data access by platform staff
-- is logged. Students and parents can request this log.
-- ============================================================

-- ── COMPLIANCE AUDIT LOG ───────────────────────────────────────────────────────
-- Immutable. Append-only. No RLS deletes permitted.

create table compliance_audit_log (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid,           -- null for system actions
  actor_role  text not null check (actor_role in ('student', 'parent', 'tutor', 'admin', 'system')),
  action      text not null,  -- e.g. 'admin.view_student_data', 'system.badge_issued'
  table_name  text,
  record_id   uuid,
  before_data jsonb,          -- null for inserts
  after_data  jsonb,          -- null for deletes
  ip_address  inet,
  user_agent  text,
  created_at  timestamptz not null default now()
);

comment on table compliance_audit_log is 'Immutable audit log. Append-only. Required by Australian Privacy Principles and Children''s Privacy Code. Never delete records from this table.';

-- Audit log: readable by admins only; append via service role (admin client)
alter table compliance_audit_log enable row level security;

create policy "audit_log_admin_select"
  on compliance_audit_log for select
  using (
    exists (
      select 1 from profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- No delete policy — records are permanent
-- Insert is handled via service role (admin client) only

-- ── LEARNING IDENTITY (REPORT CARD AI PARAGRAPHS) ─────────────────────────────

create table learning_identities (
  id              uuid primary key default gen_random_uuid(),
  student_id      uuid not null references profiles(id) on delete cascade,
  period_month    int not null check (period_month between 1 and 12),
  period_year     int not null check (period_year between 2024 and 2050),
  -- Claude-generated paragraph — gender neutral, age-appropriate tone
  generated_text  text not null,
  data_snapshot   jsonb not null,   -- the behavioural data used to generate the paragraph
  generated_at    timestamptz not null default now(),
  constraint learning_identities_period_unique unique (student_id, period_month, period_year)
);

comment on table learning_identities is 'Monthly AI-generated learning identity paragraphs. Gender neutral. Age-tier aware. Generated by Claude from real behavioural data.';

-- ── REPORT CARD CACHE ─────────────────────────────────────────────────────────

create table report_card_cache (
  id                    uuid primary key default gen_random_uuid(),
  student_id            uuid not null references profiles(id) on delete cascade,
  -- Aggregated metrics for the report card — recalculated monthly
  consistency_score     numeric(5,2) check (consistency_score between 0 and 100),
  avg_attempts_to_pass  numeric(5,2),
  retry_improvement     numeric(5,2),     -- % score improvement attempt 1 → final pass
  peak_day_of_week      int check (peak_day_of_week between 0 and 6),
  peak_hour_of_day      int check (peak_hour_of_day between 0 and 23),
  strongest_strand      text,
  weakest_strand        text,
  days_active_this_month int not null default 0,
  sections_passed_this_month int not null default 0,
  calculated_at         timestamptz not null default now(),
  constraint report_card_cache_unique unique (student_id)
);

comment on table report_card_cache is 'Pre-calculated report card metrics. Refreshed monthly via cron. Source of truth for parent reports.';

-- ── RLS ────────────────────────────────────────────────────────────────────────

alter table learning_identities enable row level security;
alter table report_card_cache enable row level security;

create policy "learning_identities_select"
  on learning_identities for select
  using (
    auth.uid() = (select user_id from profiles where id = learning_identities.student_id)
    or auth.uid() = (
      select user_id from profiles where id = (
        select parent_id from student_profiles where id = learning_identities.student_id
      )
    )
  );

create policy "report_card_cache_select"
  on report_card_cache for select
  using (
    auth.uid() = (select user_id from profiles where id = report_card_cache.student_id)
    or auth.uid() = (
      select user_id from profiles where id = (
        select parent_id from student_profiles where id = report_card_cache.student_id
      )
    )
  );

-- ── INDEXES ────────────────────────────────────────────────────────────────────

create index idx_audit_log_actor on compliance_audit_log(actor_id, created_at desc);
create index idx_audit_log_action on compliance_audit_log(action, created_at desc);
create index idx_audit_log_record on compliance_audit_log(table_name, record_id);
create index idx_learning_identities_student on learning_identities(student_id, period_year desc, period_month desc);
create index idx_report_card_cache_student on report_card_cache(student_id);
